version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    links:
      - mysql
      - redis
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_USER=zhq
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '9909:3306'
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ../redis/redis.conf:/etc/redis/redis.conf:ro
      - ../redis/data:/data
    command: redis-server /etc/redis/redis.conf
    ports:
      - '6378:6379'