version: '2'
services:
  php:
    image: my-yii2-php
    container_name: yii2_docker_demo
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    links:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_USER=zhq
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '9909:3306'
